- weapon banner
- projected time to completion
- overhaul to csv?
- way to read and reconstruct statistics
- datafil
- include non-default settings for breakdowns
- create one for weapon banner
- recreate percentage_breakdown.csv
- recreate average statistics
- show wishing distribtuion on graphs
- machine learning on primo projection?