
NUM_WISHES = 0
NUM_PRIMOS = 0
NUM_STARGLITTER = 0
NUM_GENESIS = 0

CURRENT_PITY = 0
CURRENT_GUARANTEED = False

# 6 for a c6 character
NUM_RATEUPS_DESIRED = 7

BANNER_END_DATE = banner_end_date = date(2022,10,4)